server:
  post: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: wall, stat
      url: jdbc:mysql://localhost:3306/TWTHomework20210216?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
      username: root
      password: Vicky
      initial-size: 5
      min-idle: 1
      max-acitve: 10

mybatis:
  type-aliases-package: TWT.Homework.VoteSimulator.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
